# Generated by Django 3.0.1 on 2020-01-05 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('index', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('index', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('index', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vegetable',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('index', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('_id', models.CharField(max_length=32)),
                ('index', models.IntegerField(primary_key=True, serialize=False)),
                ('guid', models.CharField(max_length=36)),
                ('has_died', models.BooleanField(default=False)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('picture', models.CharField(blank=True, max_length=255)),
                ('age', models.IntegerField()),
                ('eyeColor', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('about', models.CharField(blank=True, max_length=1024)),
                ('registered', models.DateTimeField(blank=True)),
                ('greeting', models.CharField(blank=True, max_length=256)),
                ('favouriteFood', models.CharField(blank=True, max_length=4)),
                ('compnay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colony.Company')),
                ('favouriteFruit', models.ManyToManyField(to='colony.Fruit')),
                ('favouriteVegetable', models.ManyToManyField(to='colony.Vegetable')),
                ('friends', models.ManyToManyField(to='colony.People')),
                ('tags', models.ManyToManyField(to='colony.Tag')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
