# Generated by Django 3.0.1 on 2020-01-06 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colony', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='compnay',
        ),
        migrations.AddField(
            model_name='people',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='colony.Company'),
        ),
        migrations.AlterField(
            model_name='people',
            name='_id',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='people',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='people',
            name='favouriteFruit',
            field=models.ManyToManyField(blank=True, to='colony.Fruit'),
        ),
        migrations.AlterField(
            model_name='people',
            name='favouriteVegetable',
            field=models.ManyToManyField(blank=True, to='colony.Vegetable'),
        ),
        migrations.AlterField(
            model_name='people',
            name='friends',
            field=models.ManyToManyField(blank=True, to='colony.People'),
        ),
        migrations.AlterField(
            model_name='people',
            name='tags',
            field=models.ManyToManyField(blank=True, to='colony.Tag'),
        ),
    ]
