# Generated by Django 3.0.1 on 2020-01-11 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colony', '0002_auto_20200106_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('colony.people',),
        ),
        migrations.RemoveField(
            model_name='people',
            name='favouriteFood',
        ),
    ]
